spring.application.name=aniversex-crud

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# MySQL database settings
spring.datasource.url=jdbc:mysql://localhost:3306/aniversex_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Run SQL scripts on startup
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
