DROP TABLE IF EXISTS anime;

CREATE TABLE anime (
    anime_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    episodes INT NOT NULL,
    rating DOUBLE NOT NULL,
    short_review VARCHAR(500) NOT NULL
);
